### ISSUE TITLE
Dependency and connectivity issues

### ISSUE THREAD

**Issue by andreiko** [the-kid89/redis_proxy#1]
Hey Emett,

My name is Andrey, I'm a software engineer here at Segment and I'm running into some issues trying to start the tests or the server. Attaching the output of `make test` command (1st file):
https://gist.github.com/andreiko/a62e01d394e73ca85d4bc05f56c8a1f5#file-gistfile1-txt

I tried to follow the suggestion there and added an extra step before `CMD`:
```
RUN mix local.rebar --force
```

After that it progressed further but seemingly had trouble connecting to the redis container:
https://gist.github.com/andreiko/a62e01d394e73ca85d4bc05f56c8a1f5#file-gistfile2-txt

An arbitrary debian container running on the same docker network didn't have any trouble connecting the redis server by its alias.

**Comment by Sudo-Kid** [comment]
Hello Andrey,

Sorry about that. I didn't run into that rebar3 issue on my system at home before I pushed the code. It could have been a state issue on my side maybe the change in the Elixir container that was push on Sunday. I updated the Docker file to include `RUN mix local.rebar --force` and it seems to have fixed the problem.

I was also able to track down what was causing the issue with the redis server connection. It turns out that the use of `"` in `- REDIS_HOST="redis"` was the cause. I removed them and ran the tests again with success.

I'm sure there are still many issues that need fixing and performance tuning so please do keep me posted if you run into any other issues.

Thank you,
Emett

**Comment by andreiko** [comment]
Thank you, Emett!
